name: Release Listeningway Addon

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Read version from VERSION.txt
        id: get_version
        run: |
          VERSION=$(cat dist/VERSION.txt | tr -d '\r\n')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Prepare release notes from template
        id: prep_release_notes
        run: |
          sed "s/{{VERSION}}/${{ steps.get_version.outputs.version }}/g" docs/template/release.md > release_body.md

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "v${{ steps.get_version.outputs.version }}" >/dev/null 2>&1; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create tag if needed
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ steps.get_version.outputs.version }}
          git push origin v${{ steps.get_version.outputs.version }}

      - name: Zip release files
        run: |
          VERSION=$(cat dist/VERSION.txt | tr -d '\r\n')
          cd dist
          zip Listeningway-${VERSION}.zip Listeningway.addon Listeningway.fx ListeningwayUniforms.fxh
          cd ..

      - name: Create or update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Listeningway v${{ steps.get_version.outputs.version }}
          body_path: release_body.md
          files: |
            dist/Listeningway-${{ steps.get_version.outputs.version }}.zip
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
